"""initial schema

Revision ID: 1703f317ccfa
Revises: 
Create Date: 2026-04-10 21:33:19.670550

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1703f317ccfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('draft_subject', sa.String(length=255), nullable=False),
    sa.Column('draft_preheader', sa.String(length=255), nullable=True),
    sa.Column('draft_body_text', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('template_key', sa.String(length=255), nullable=False),
    sa.Column('audience_name', sa.String(length=255), nullable=False),
    sa.Column('delivery_topic', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('schedule_cron', sa.String(length=255), nullable=True),
    sa.Column('schedule_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletters_id'), 'newsletters', ['id'], unique=False)
    op.create_index(op.f('ix_newsletters_slug'), 'newsletters', ['slug'], unique=True)
    op.create_index(op.f('ix_newsletters_status'), 'newsletters', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initialized', sa.Boolean(), nullable=False),
    sa.Column('operator_user_id', sa.Integer(), nullable=True),
    sa.Column('bootstrap_disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('newsletter_recipients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppression_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('newsletter_id', 'email', name='uq_newsletter_recipient_email')
    )
    op.create_index(op.f('ix_newsletter_recipients_email'), 'newsletter_recipients', ['email'], unique=False)
    op.create_index(op.f('ix_newsletter_recipients_id'), 'newsletter_recipients', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_recipients_newsletter_id'), 'newsletter_recipients', ['newsletter_id'], unique=False)
    op.create_index(op.f('ix_newsletter_recipients_unsubscribe_token'), 'newsletter_recipients', ['unsubscribe_token'], unique=True)
    op.create_table('newsletter_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('trigger_mode', sa.String(length=64), nullable=False),
    sa.Column('run_status', sa.String(length=32), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('template_key', sa.String(length=255), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_subject', sa.String(length=255), nullable=False),
    sa.Column('snapshot_preheader', sa.String(length=255), nullable=True),
    sa.Column('snapshot_body_text', sa.Text(), nullable=False),
    sa.Column('snapshot_recipient_emails', sa.Text(), nullable=False),
    sa.Column('delivery_outcomes', sa.Text(), nullable=False),
    sa.Column('result_mode', sa.String(length=64), nullable=True),
    sa.Column('result_message', sa.Text(), nullable=True),
    sa.Column('attempt_key', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('rendered_subject', sa.String(length=255), nullable=True),
    sa.Column('rendered_preheader', sa.String(length=255), nullable=True),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('rendered_plain_text', sa.Text(), nullable=True),
    sa.Column('snapshot_prompt', sa.Text(), nullable=True),
    sa.Column('snapshot_newsletter_name', sa.String(length=255), nullable=True),
    sa.Column('snapshot_newsletter_slug', sa.String(length=255), nullable=True),
    sa.Column('snapshot_delivery_topic', sa.String(length=255), nullable=True),
    sa.Column('snapshot_status_at_run', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['newsletter_id'], ['newsletters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_runs_attempt_key'), 'newsletter_runs', ['attempt_key'], unique=True)
    op.create_index(op.f('ix_newsletter_runs_id'), 'newsletter_runs', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_runs_newsletter_id'), 'newsletter_runs', ['newsletter_id'], unique=False)
    op.create_index(op.f('ix_newsletter_runs_run_status'), 'newsletter_runs', ['run_status'], unique=False)
    op.create_index(op.f('ix_newsletter_runs_trigger_mode'), 'newsletter_runs', ['trigger_mode'], unique=False)
    op.create_table('newsletter_run_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_status', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['newsletter_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_newsletter_run_events_id'), 'newsletter_run_events', ['id'], unique=False)
    op.create_index(op.f('ix_newsletter_run_events_run_id'), 'newsletter_run_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_newsletter_run_events_run_id'), table_name='newsletter_run_events')
    op.drop_index(op.f('ix_newsletter_run_events_id'), table_name='newsletter_run_events')
    op.drop_table('newsletter_run_events')
    op.drop_index(op.f('ix_newsletter_runs_trigger_mode'), table_name='newsletter_runs')
    op.drop_index(op.f('ix_newsletter_runs_run_status'), table_name='newsletter_runs')
    op.drop_index(op.f('ix_newsletter_runs_newsletter_id'), table_name='newsletter_runs')
    op.drop_index(op.f('ix_newsletter_runs_id'), table_name='newsletter_runs')
    op.drop_index(op.f('ix_newsletter_runs_attempt_key'), table_name='newsletter_runs')
    op.drop_table('newsletter_runs')
    op.drop_index(op.f('ix_newsletter_recipients_unsubscribe_token'), table_name='newsletter_recipients')
    op.drop_index(op.f('ix_newsletter_recipients_newsletter_id'), table_name='newsletter_recipients')
    op.drop_index(op.f('ix_newsletter_recipients_id'), table_name='newsletter_recipients')
    op.drop_index(op.f('ix_newsletter_recipients_email'), table_name='newsletter_recipients')
    op.drop_table('newsletter_recipients')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_newsletters_status'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_slug'), table_name='newsletters')
    op.drop_index(op.f('ix_newsletters_id'), table_name='newsletters')
    op.drop_table('newsletters')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
